import { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useAuth } from '../contexts/AuthContext';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import TransactionTable from '../components/TransactionTable';
import ExpenseTable from '../components/ExpenseTable';
import ProjectTable from '../components/ProjectTable';
import TransactionFormModal from '../components/TransactionFormModal';
import ExpenseFormModal from '../components/ExpenseFormModal';
import ProjectFormModal from '../components/ProjectFormModal';
import { isApproved, ENTRY_STATUS } from '../constants/app';
import {
  fetchTransactions,
  approveTransaction,
  editTransaction,
  removeTransaction,
  removeTransactionsBulk
} from '../store/transactions/transactionsSlice';
import { fetchExpenses, approveExpense, editExpense, removeExpense } from '../store/expenses/expensesSlice';
import { fetchProjects, approveProject, editProject, removeProject } from '../store/projects/projectsSlice';
import { useClientOptions } from '../hooks/useClientOptions';
import { PROJECT_TYPE_OPTIONS } from '../constants/projectTypes';
import { prepareProjectForFirestore } from '../utils/project';
import { syncMonthlyBrokerageExpense } from '../utils/ensureMonthlyBrokerageExpense';
import {
  EMPTY_TRANSACTION_FORM,
  EMPTY_EXPENSE_FORM,
  EMPTY_PROJECT_FORM,
  transactionToFormValues,
  expenseToFormValues,
  projectToFormValues
} from '../utils/formValues';
import ErrorAlert from '../components/ErrorAlert';
import PageContainer from '../components/PageContainer';
import Tabs from '../components/Tabs';
import DeleteConfirmModal from '../components/DeleteConfirmModal';
import ApproveAllConfirmModal from '../components/ApproveAllConfirmModal';

const PendingRequests = () => {
  const dispatch = useDispatch();
  const { user } = useAuth();

  const transactions = useSelector((state) => state.transactions.items);
  const expenses = useSelector((state) => state.expenses.items);
  const projects = useSelector((state) => state.projects.items);
  const isLoadingT = useSelector((state) => state.transactions.isLoading);
  const isLoadingE = useSelector((state) => state.expenses.isLoading);
  const isLoadingP = useSelector((state) => state.projects.isLoading);
  const errorT = useSelector((state) => state.transactions.error);
  const errorE = useSelector((state) => state.expenses.error);
  const errorP = useSelector((state) => state.projects.error);

  const clientOptions = useClientOptions(projects);

  const [editingTransactionId, setEditingTransactionId] = useState(null);
  const [editingExpenseId, setEditingExpenseId] = useState(null);
  const [editingProjectId, setEditingProjectId] = useState(null);
  const [initialValuesTransaction, setInitialValuesTransaction] = useState(EMPTY_TRANSACTION_FORM);
  const [initialValuesExpense, setInitialValuesExpense] = useState(EMPTY_EXPENSE_FORM);
  const [initialValuesProject, setInitialValuesProject] = useState(EMPTY_PROJECT_FORM);
  const [editingTransaction, setEditingTransaction] = useState(null);
  const [isResetTxOpen, setIsResetTxOpen] = useState(false);
  const [isResettingTx, setIsResettingTx] = useState(false);

  const pendingTransactions = useMemo(
    () => (transactions || []).filter((t) => !isApproved(t)),
    [transactions]
  );
  const pendingExpenses = useMemo(
    () => (expenses || []).filter((e) => !isApproved(e)),
    [expenses]
  );
  const pendingProjects = useMemo(
    () => (projects || []).filter((p) => !isApproved(p)),
    [projects]
  );

  const currentUserId = user?.uid ?? null;

  const resettablePendingTransactionIds = useMemo(
    () =>
      pendingTransactions
        .filter(
          (t) =>
            t?.status === ENTRY_STATUS.PENDING &&
            t?.createdBy &&
            t.createdBy === currentUserId &&
            t?.autoGenerated
        )
        .map((t) => t.id)
        .filter(Boolean),
    [pendingTransactions, currentUserId]
  );

  useEffect(() => {
    document.title = 'Pending Requests | FinHub';
  }, []);

  useEffect(() => {
    dispatch(fetchTransactions());
    dispatch(fetchExpenses());
    dispatch(fetchProjects());
  }, [dispatch]);

  const canApprovePending = () => !!currentUserId;

  const onApproveTransaction = async (id) => {
    if (!currentUserId) return;
    await dispatch(approveTransaction({ transactionId: id, approvedBy: currentUserId })).unwrap();
  };
  const onApproveExpense = async (id) => {
    if (!currentUserId) return;
    await dispatch(approveExpense({ expenseId: id, approvedBy: currentUserId })).unwrap();
  };
  const onApproveProject = async (id) => {
    if (!currentUserId) return;
    await dispatch(approveProject({ projectId: id, approvedBy: currentUserId })).unwrap();
  };

  const [approvingAll, setApprovingAll] = useState({ t: false, e: false, p: false });
  const [approveAllConfirm, setApproveAllConfirm] = useState(null);
  const [activeTab, setActiveTab] = useState('transactions');

  const approvableTransactionIds = pendingTransactions.map((t) => t.id).filter(Boolean);
  const approvableExpenseIds = pendingExpenses.map((e) => e.id).filter(Boolean);
  const approvableProjectIds = pendingProjects.map((p) => p.id).filter(Boolean);

  const onApproveAllTransactions = async () => {
    if (!currentUserId || approvableTransactionIds.length === 0) return;
    setApprovingAll((prev) => ({ ...prev, t: true }));
    try {
      await Promise.all(
        approvableTransactionIds.map((id) =>
          dispatch(approveTransaction({ transactionId: id, approvedBy: currentUserId })).unwrap()
        )
      );
    } finally {
      setApprovingAll((prev) => ({ ...prev, t: false }));
    }
  };

  const onResetMyAutoGeneratedTransactions = async () => {
    if (!currentUserId || resettablePendingTransactionIds.length === 0) return;
    setIsResettingTx(true);
    try {
      await dispatch(removeTransactionsBulk(resettablePendingTransactionIds)).unwrap();
    } finally {
      setIsResettingTx(false);
      setIsResetTxOpen(false);
    }
  };
  const onApproveAllExpenses = async () => {
    if (!currentUserId || approvableExpenseIds.length === 0) return;
    setApprovingAll((prev) => ({ ...prev, e: true }));
    try {
      await Promise.all(
        approvableExpenseIds.map((id) =>
          dispatch(approveExpense({ expenseId: id, approvedBy: currentUserId })).unwrap()
        )
      );
    } finally {
      setApprovingAll((prev) => ({ ...prev, e: false }));
    }
  };
  const onApproveAllProjects = async () => {
    if (!currentUserId || approvableProjectIds.length === 0) return;
    setApprovingAll((prev) => ({ ...prev, p: true }));
    try {
      await Promise.all(
        approvableProjectIds.map((id) =>
          dispatch(approveProject({ projectId: id, approvedBy: currentUserId })).unwrap()
        )
      );
    } finally {
      setApprovingAll((prev) => ({ ...prev, p: false }));
    }
  };

  const isInitialLoadingT = isLoadingT && !(transactions?.length);
  const isInitialLoadingE = isLoadingE && !(expenses?.length);
  const isInitialLoadingP = isLoadingP && !(projects?.length);

  const openEditTransaction = (transaction) => {
    setEditingTransaction(transaction || null);
    setInitialValuesTransaction(transactionToFormValues(transaction));
    setEditingTransactionId(transaction.id);
  };

  const openEditExpense = (expense) => {
    setInitialValuesExpense(expenseToFormValues(expense));
    setEditingExpenseId(expense.id);
  };

  const openEditProject = (project) => {
    setInitialValuesProject(projectToFormValues(project));
    setEditingProjectId(project.id);
  };

  const closeEditTransaction = () => {
    setEditingTransactionId(null);
    setEditingTransaction(null);
  };
  const closeEditExpense = () => setEditingExpenseId(null);
  const closeEditProject = () => setEditingProjectId(null);

  const submitEditTransaction = async (transactionData) => {
    if (!editingTransactionId) return;
    await dispatch(editTransaction({ transactionId: editingTransactionId, transactionData })).unwrap();
    await syncMonthlyBrokerageExpense(dispatch, {
      transactionData,
      previousTransaction: editingTransaction,
      projects,
      transactions,
      expenses,
      excludeTxId: editingTransactionId,
      createdBy: user?.uid || null
    });
    setEditingTransactionId(null);
    setEditingTransaction(null);
  };

  const submitEditExpense = async (expenseData) => {
    if (!editingExpenseId) return;
    await dispatch(editExpense({ expenseId: editingExpenseId, expenseData })).unwrap();
    setEditingExpenseId(null);
  };

  const submitEditProject = async (projectData) => {
    if (!editingProjectId) return;
    await dispatch(
      editProject({ projectId: editingProjectId, projectData: prepareProjectForFirestore(projectData) })
    ).unwrap();
    setEditingProjectId(null);
  };

  const onDeleteTransaction = async (id) => {
    await dispatch(removeTransaction(id)).unwrap();
  };

  const onDeleteExpense = async (id) => {
    await dispatch(removeExpense(id)).unwrap();
  };

  const onDeleteProject = async (id) => {
    await dispatch(removeProject(id)).unwrap();
  };

  const pendingTabs = [
    { id: 'transactions', label: 'Transactions', shortLabel: 'Trans.', badge: pendingTransactions.length },
    { id: 'expenses', label: 'Expenses', badge: pendingExpenses.length },
    { id: 'projects', label: 'Projects', badge: pendingProjects.length }
  ];

  return (
    <PageContainer>
      <PageHeader title="Pending Requests" />

      <ErrorAlert messages={[errorT, errorE, errorP].filter(Boolean)} />

      <div className="space-y-0">
        <Tabs tabs={pendingTabs} activeId={activeTab} onChange={setActiveTab}>
          {activeTab === 'transactions' && (
            <TransactionTable
              transactions={pendingTransactions}
              title="Pending Transactions"
              isLoading={isInitialLoadingT}
              onEdit={(item) => openEditTransaction(item)}
              onApprove={(id) => onApproveTransaction(id)}
              onDelete={onDeleteTransaction}
              getCanApprove={canApprovePending}
              emptyTitle="No pending transactions"
              emptyDescription="Pending transactions will appear here for review"
              titleActions={
                <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 w-full sm:w-auto">
                  {resettablePendingTransactionIds.length > 0 ? (
                    <Button
                      variant="danger"
                      onClick={() => setIsResetTxOpen(true)}
                      disabled={isResettingTx}
                      size="sm"
                    >
                      {isResettingTx ? 'Resetting…' : `Reset my auto-generated (${resettablePendingTransactionIds.length})`}
                    </Button>
                  ) : null}
                  {approvableTransactionIds.length > 0 ? (
                    <Button onClick={() => setApproveAllConfirm('transactions')} disabled={approvingAll.t} size="sm">
                      {approvingAll.t ? 'Approving…' : `Approve all (${approvableTransactionIds.length})`}
                    </Button>
                  ) : null}
                </div>
              }
            />
          )}
          {activeTab === 'expenses' && (
            <ExpenseTable
              expenses={pendingExpenses}
              title="Pending Expenses"
              isLoading={isInitialLoadingE}
              onEdit={(item) => openEditExpense(item)}
              onApprove={(id) => onApproveExpense(id)}
              onDelete={onDeleteExpense}
              getCanApprove={canApprovePending}
              projects={projects}
              emptyTitle="No pending expenses"
              emptyDescription="Pending expenses will appear here for review"
              titleActions={
                approvableExpenseIds.length > 0 ? (
                  <Button onClick={() => setApproveAllConfirm('expenses')} disabled={approvingAll.e} size="sm">
                    {approvingAll.e ? 'Approving…' : `Approve all (${approvableExpenseIds.length})`}
                  </Button>
                ) : null
              }
            />
          )}
          {activeTab === 'projects' && (
            <ProjectTable
              projects={pendingProjects}
              title="Pending Projects"
              isLoading={isInitialLoadingP}
              onEdit={(item) => openEditProject(item)}
              onApprove={(id) => onApproveProject(id)}
              onDelete={onDeleteProject}
              getCanApprove={canApprovePending}
              emptyTitle="No pending projects"
              emptyDescription="Pending projects will appear here for review"
              titleActions={
                approvableProjectIds.length > 0 ? (
                  <Button onClick={() => setApproveAllConfirm('projects')} disabled={approvingAll.p} size="sm">
                    {approvingAll.p ? 'Approving…' : `Approve all (${approvableProjectIds.length})`}
                  </Button>
                ) : null
              }
            />
          )}
        </Tabs>
      </div>

      <TransactionFormModal
        key={editingTransactionId ? `tx-${editingTransactionId}` : 'pending-tx-new'}
        isOpen={!!editingTransactionId}
        onClose={closeEditTransaction}
        title="Edit Transaction"
        initialValues={initialValuesTransaction}
        onSubmit={submitEditTransaction}
        isSaving={isLoadingT}
        projects={projects}
        clientOptions={clientOptions}
        transactions={transactions}
        editingTransactionId={editingTransactionId}
        editingTransaction={editingTransaction}
      />

      <ExpenseFormModal
        key={editingExpenseId ? `expense-${editingExpenseId}` : 'pending-expense-new'}
        isOpen={!!editingExpenseId}
        onClose={closeEditExpense}
        title="Edit Expense"
        initialValues={initialValuesExpense}
        onSubmit={submitEditExpense}
        isSaving={isLoadingE}
      />

      <ProjectFormModal
        key={editingProjectId ? `project-${editingProjectId}` : 'pending-project-new'}
        isOpen={!!editingProjectId}
        onClose={closeEditProject}
        title="Edit Project"
        clientOptions={clientOptions}
        projectTypeOptions={PROJECT_TYPE_OPTIONS}
        initialValues={initialValuesProject}
        onSubmit={submitEditProject}
        isSaving={isLoadingP}
        projects={projects}
      />

      <DeleteConfirmModal
        isOpen={isResetTxOpen}
        onClose={() => setIsResetTxOpen(false)}
        onConfirm={onResetMyAutoGeneratedTransactions}
        title="Reset auto-generated transactions"
        message="Delete your pending auto-generated transactions so you can generate them again with updated rules."
        isDeleting={isResettingTx}
      />

      <ApproveAllConfirmModal
        isOpen={approveAllConfirm === 'transactions'}
        onClose={() => setApproveAllConfirm(null)}
        onConfirm={onApproveAllTransactions}
        count={approvableTransactionIds.length}
        entityLabel="transactions"
        isApproving={approvingAll.t}
      />
      <ApproveAllConfirmModal
        isOpen={approveAllConfirm === 'expenses'}
        onClose={() => setApproveAllConfirm(null)}
        onConfirm={onApproveAllExpenses}
        count={approvableExpenseIds.length}
        entityLabel="expenses"
        isApproving={approvingAll.e}
      />
      <ApproveAllConfirmModal
        isOpen={approveAllConfirm === 'projects'}
        onClose={() => setApproveAllConfirm(null)}
        onConfirm={onApproveAllProjects}
        count={approvableProjectIds.length}
        entityLabel="projects"
        isApproving={approvingAll.p}
      />
    </PageContainer>
  );
};

export default PendingRequests;
